plugins {
    alias libs.plugins.android.application
}

def localProps = new Properties()
def localPropsFile = rootProject.file('local.properties')
if (localPropsFile.exists()) {
    localPropsFile.withInputStream {
        localProps.load(it)
    }
}

android {
    namespace = 'com.fongmi.android.tv'

    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        applicationId "com.fongmi.android.tv"
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
        versionCode 556
        versionName "5.5.6"
        ndk {
            abiFilters "armeabi-v7a"
        }
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString(), "eventBusIndex": "com.fongmi.android.tv.event.EventIndex"]
            }
        }
    }

    flavorDimensions = ["mode"]

    productFlavors {
        leanback {
            dimension "mode"
        }
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    signingConfigs {
        release {
            if (localProps['storeFile']) {
                storeFile rootProject.file(localProps['storeFile'])
                keyAlias localProps['keyAlias']
                keyPassword localProps['storePassword']
                storePassword localProps['storePassword']
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            if (localProps['storeFile']) signingConfig = signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro', 'proguard-rules-media.pro'
        }
    }

    configurations.configureEach {
        exclude group: 'stax', module: 'stax-api'
        exclude group: 'xpp3', module: 'xpp3'
        exclude group: 'com.android.support'
        resolutionStrategy {
            force libs.okhttp
        }
    }

    lint {
        disable 'UnsafeOptInUsageError'
        disable 'ExpiredTargetSdkVersion'
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

androidComponents {
    onVariants(selector()) { variant ->
        def type = variant.buildType
        variant.outputs.each { output ->
            output.outputFileName.set(type == 'release' ? "infuse.apk" : "infuse-${type}.apk")
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.aar"])
    implementation project(':catvod')
    implementation project(':quickjs')
    implementation libs.appcompat
    implementation libs.lifecycle.service
    implementation libs.media
    implementation libs.palette
    implementation libs.recyclerview
    implementation libs.room.runtime
    implementation libs.splashscreen
    implementation libs.swiperefreshlayout
    implementation libs.viewpager2
    implementation libs.android.gif.drawable
    implementation libs.bundles.glide
    implementation libs.customactivityoncrash
    implementation libs.eventbus
    implementation libs.flexbox
    implementation libs.rtmp.client
    implementation libs.lottie
    implementation libs.material
    implementation libs.materialdesigncolors
    implementation libs.nanohttpd
    implementation libs.permissionx
    implementation libs.simple.xml
    implementation libs.textdrawable
    leanbackImplementation libs.leanback
    leanbackImplementation libs.androidautosize
    implementation("com.alphacephei:vosk-android:${libs.versions.vosk.get()}@aar")
    implementation("net.java.dev.jna:jna:${libs.versions.jna.get()}@aar")
    annotationProcessor libs.room.compiler
    annotationProcessor libs.eventbus.annotation.processor
    annotationProcessor libs.glide.compiler
    coreLibraryDesugaring libs.desugar
    testImplementation libs.junit
    testImplementation libs.robolectric
}